### ISSUE TITLE
Drop Table Spawns

### ISSUE THREAD

**Issue by BrandonT80** [ASharpPen/Valheim.DropThat#124]
Anything put in the drop_that.drop_table.cfg spawns at spawn rather than at the location.

For example:
Birch half logs broken will spawn the normal items at the log, but any additional items at the spawn location.

![e68b37a15cce1fa776a685fb56f8bef5](https://user-images.githubusercontent.com/31973893/150846554-3eb4fc8b-80a4-4fb4-9271-15689a99a2a1.jpg)
![0e6c83a819bbac48185665aa88365cc1](https://user-images.githubusercontent.com/31973893/150846559-73d51547-9a11-47fe-9294-e979039d6231.png)

**Comment by ASharpPen** [comment]
Not able to replicate. Please attach your bepinex log file, for this happening.

**Comment by ASharpPen** [comment]
Nevermind, found the problem. Working on a fix.
