### ISSUE TITLE
Cannot generate Magic rarity (or higher) with EpicLoot

### ISSUE THREAD

**Issue by trainchoo** [ASharpPen/Valheim.DropThat#135]
Using this config option I cannot spawn a magic or rare item. It always spawns as non-magic. What am I doing wrong?

            [TreasureChest_meadows]
            SetDropChance=100
            SetDropOnlyOnce=True
            SetDropMin=1
            SetDropMax=1
            
            [TreasureChest_meadows.0]
            PrefabName=Hoe
            SetTemplateWeight=1
            
            [TreasureChest_meadows.0.EpicLoot]
            RarityWeightRare=100

Drop that version: 2.3.2
Epic Loot: 0.8.8
BepInEx: 5.4.1900
Valheim: 0.207.20

I'm only editing the "drop_that.drop_table.cfg" file.

**Comment by ASharpPen** [comment]
Seems to be a bug, I will look into it.
