### ISSUE TITLE
AmountMin AmountMax not working

### ISSUE THREAD

**Issue by dirtboggle** [ASharpPen/Valheim.DropThat#18]
Items are not dropping in intended quantities.

Running BepInEx v5.4.602 and DropThat v1.2.0

[drop_that.supplemental.bosses.cfg.txt](https://github.com/ASharpPen/Valheim.DropThat/files/6059331/drop_that.supplemental.bosses.cfg.txt)

**Comment by ASharpPen** [comment]
Interesting, there is nothing particularly complex in Drop That that should cause that.

Can you clarify on what is not being dropped as intended? Your config looks fine overall to me.

**Comment by dirtboggle** [comment]
The cause was a misinterpretation of OnePerPlayer. I thought it would multiply the drop per player, but it overrules the AmountMin with literally one per player. So I was getting drops of 1 for items in my table that should have been stacks. Have not tested with other players.
