### ISSUE TITLE
unable to get it to work 

### ISSUE THREAD

**Issue by DakuTatsu** [ASharpPen/Valheim.DropThat#7]
i have added in a drop listing for Boar  `[Boar.4]

# Setting type: String
# Default value: 
ItemName = Dragon Tear

# Setting type: Int32
# Default value: 1
AmountMin = 1

# Setting type: Int32
# Default value: 1
AmountMax = 2

# Setting type: Single
# Default value: 1
Chance = 1

# Setting type: Boolean
# Default value: false
OnePerPlayer = false

# Setting type: Boolean
# Default value: false
LevelMultiplier = true

# Setting type: Boolean
# Default value: true
Enabled = true`
this is in the tables as a test to see if i can figure out what all is needed 
for the DT settings 
clear all existing = false 
clear all existing when modified = false
always append is false 
enable debug true 

from my understanding boars have 3 drops  the hide meat and trophy  so i did the boar.4 to make  a new drop  but the drop does not show up at all

**Comment by ASharpPen** [comment]
Looks like the prefab is wrong.
Did you see a warning in the log saying it couldn't find "Dragon Tear"? It should show for situations like yours.

You can go to https://gist.github.com/Sonata26/e2b85d53e125fb40081b18e2aee6d584 to find a full list of prefab names.
