### ISSUE TITLE
SetQualityLevel / EpicLoot

### ISSUE THREAD

**Issue by Voidheart90** [ASharpPen/Valheim.DropThat#83]
Was using my own mobs to test from RRR with "drop_that.supplemental.*" noticed the SetQualityLevel was setting everything to Quality : 1 regardless of configuration. Tested it also with Vanilla mobs such as the blob in "drop_that.tables.cfg".

Epic Loot was't applied even with a high Weight.
Using the latest version of Epic Loot 0.8.0 (Possibly due to the 0.7.0 supported) So uninstalling EpicLoot and removing the EpicLoot config section for the drop still yielded a Quality : 1

```
[Blob.2]
ItemName = ShieldWood
Enabled = True
AmountMin = 1
AmountMax = 1
Chance = 1
SetQualityLevel=3

[Blob.2.EpicLoot]
RarityWeightEpic=500
```

**Debug Information:**
```
[Info   :Drop That!] [Blob(Clone)]: 2 existing drops in table.
[Info   :Drop That!] [Blob(Clone)]: Inserting drop EssenceRare at index '2'.
[Info   :Drop That!] [Blob(Clone)]: 3 existing drops in table.
[Info   :Drop That!] [Blob(Clone)]: Inserting drop DustRare at index '3'.
[Info   :Drop That!] [Blob(Clone)]: 4 existing drops in table.
[Info   :Drop That!] [Blob(Clone)]: Inserting drop ReagentRare at index '4'.
[Info   :Drop That!] [Blob(Clone)]: 5 existing drops in table.
[Info   :Drop That!] [Blob(Clone)]: Inserting drop ShieldWood at index '5'.
```

Went back and compiled the repository so I could get full debug information

```
[Info   :Drop That!] [RRRM_VoidGhostWarrior(Clone)]: 1 existing drops in table.
[Info   :Drop That!] [RRRM_VoidGhostWarrior]: Removing overriden item 'AmberPearl' at index '0'.
[Info   :Drop That!] [RRRM_VoidGhostWarrior(Clone)]: Inserting drop ArmorBronzeChest at index '0'.
[Info   : Unity Log] 06/06/2021 14:01:14: hit mine rock 2

[Info   : Unity Log] 06/06/2021 14:01:14: Suport time 0.03051758

[Warning:Drop That!] Unable to carry drop due to being null for RRRM_VoidGhostWarrior(Clone) (CharacterDrop).
[Info   :Drop That!] Setting temp drop cache 0:-361547264
[Info   :Drop That!] Found temp drop cache for -361547264
[Info   :Drop That!] Successfully retrieved config from temp drop cache
[Info   :Drop That!] Attempting to apply modifiers to item ArmorBronzeChest(Clone):1434614656
[Info   :Drop That!] Possible drops: ArmorBronzeChest:1
[Info   :Drop That!] [OnSpawnedItem] Count: 0, Index: 0
[Info   :Drop That!] No config for item ArmorBronzeChest(Clone) at index 0
[Info   :Drop That!] [OnSpawnLoop] Count: 0, Index: 0
```

The config i used for this

```
[RRRM_VoidGhostWarrior.0]
ItemName = ArmorBronzeChest
Enabled = True
AmountMin = 1
AmountMax = 1
Chance = 1
LevelMultiplier=false

SetQualityLevel=5
SetAmountLimit=1

ConditionMinLevel=1
ConditionMaxLevel=2
ConditionBiomes=Blackforest,Meadows
```

**Comment by ASharpPen** [comment]
Hm... This looks suspiciously like I uploaded the wrong dll...

You shouldn't be seeing a lot of that debug info unless it was build in debug mode, which is not the one thats supposed to be released. I will get it fixed later today.

**Comment by ASharpPen** [comment]
Looked into what was uploaded. Update your Drop That, you are not using the correct version. No clue where you got the version you have from (maybe Vortex is being funny again, if you are using that).

**Comment by Voidheart90** [comment]
Hi sorry, no I downloaded the repository and compiled it myself so I could see extra debug information trying to pinpoint why it wasn't setting the Quality Level of the shield/armor.

I had just posted the debug information to you so you could have more in-depth on the problem

**Comment by ASharpPen** [comment]
Ah, that explains a lot. I was very confused as to how that managed to occur.

You are right though in that helping a bit, since I spot a line saying "No config for item ArmorBronzeChest". Sorry for what was probably a very un-fun process of getting the references in order, to make it compile.

Can you post me your whole log output file? 
I would like to see if there are in mods in the list that could potentially affect the part of the code that is responsible for applying modifiers. I may need to do additional stabilization to this already quite volatile area of the code, or just fix it if it turns out to be me being bad at counting.

**Comment by Voidheart90** [comment]
https://pastebin.com/Gtncfz6L

Used PasteBin to upload the log, My first test was killing 3 PhantomGhostWarrior with a MaceBronze then spawned in a few more and used the console command to kill them

**Comment by ASharpPen** [comment]
~~I have been unable to reproduce this. I am starting to think this may be a conflict with another mod.~~
Scratch that, found a setup that caused it. I think I am on to it

**Comment by Voidheart90** [comment]
That's good news, I noticed it was a modifier if applied to an condition? such as ConditionLevel so made sure to use an condition trigger the DropExtended because I only skimmed through some of the code was trying to trigger the SetQualityLevel event

**Comment by ASharpPen** [comment]
It's in the modifier section indeed. Probably the most complex part of the whole mod. Need to carry config information and re-associate it with the correct drop after going through a serialization and deserialization process, as well as a couple of other "fun" issues.

Basically, everything after generating the drop list is madness
